package com.heidiaandahl.service;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.Generated;

/**
 * DataItem is a class generated by robopojogenerator to handle information from BLS api calls.
 */
@Generated("com.robohorse.robopojogenerator")
public class DataItem{

	@JsonProperty("period")
	private String period;

	@JsonProperty("year")
	private String year;

	@JsonProperty("periodName")
	private String periodName;

	@JsonProperty("value")
	private String value;

	@JsonProperty("footnotes")
	private List<FootnotesItem> footnotes;

	@JsonProperty("latest")
	private String latest;

	/**
	 * Set period.
	 *
	 * @param period the period
	 */
	public void setPeriod(String period){
		this.period = period;
	}

	/**
	 * Get period string.
	 *
	 * @return the string
	 */
	public String getPeriod(){
		return period;
	}

	/**
	 * Set year.
	 *
	 * @param year the year
	 */
	public void setYear(String year){
		this.year = year;
	}

	/**
	 * Get year string.
	 *
	 * @return the string
	 */
	public String getYear(){
		return year;
	}

	/**
	 * Set period name.
	 *
	 * @param periodName the period name
	 */
	public void setPeriodName(String periodName){
		this.periodName = periodName;
	}

	/**
	 * Get period name string.
	 *
	 * @return the string
	 */
	public String getPeriodName(){
		return periodName;
	}

	/**
	 * Set value.
	 *
	 * @param value the value
	 */
	public void setValue(String value){
		this.value = value;
	}

	/**
	 * Get value string.
	 *
	 * @return the string
	 */
	public String getValue(){
		return value;
	}

	/**
	 * Set footnotes.
	 *
	 * @param footnotes the footnotes
	 */
	public void setFootnotes(List<FootnotesItem> footnotes){
		this.footnotes = footnotes;
	}

	/**
	 * Get footnotes list.
	 *
	 * @return the list
	 */
	public List<FootnotesItem> getFootnotes(){
		return footnotes;
	}

	/**
	 * Set latest.
	 *
	 * @param latest the latest
	 */
	public void setLatest(String latest){
		this.latest = latest;
	}

	/**
	 * Get latest string.
	 *
	 * @return the string
	 */
	public String getLatest(){
		return latest;
	}

	@Override
 	public String toString(){
		return 
			"DataItem{" + 
			"period = '" + period + '\'' + 
			",year = '" + year + '\'' + 
			",periodName = '" + periodName + '\'' + 
			",value = '" + value + '\'' + 
			",footnotes = '" + footnotes + '\'' + 
			",latest = '" + latest + '\'' + 
			"}";
		}
}