package com.heidiaandahl.service;

import javax.annotation.Generated;

/**
 * FootnotesItem is a class generated by robopojogenerator to handle information from BLS api calls.
 */
@Generated("com.robohorse.robopojogenerator")
public class FootnotesItem{

	@Override
 	public String toString(){
		return 
			"FootnotesItem{" + 
			"}";
		}
}