package com.heidiaandahl.service;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.Generated;

/**
 * Response is a class generated by robopojogenerator to handle information from BLS api calls.
 */
@Generated("com.robohorse.robopojogenerator")
public class Response{

	@JsonProperty("Results")
	private Results results;

	@JsonProperty("responseTime")
	private int responseTime;

	@JsonProperty("message")
	private List<String> message;

	@JsonProperty("status")
	private String status;

	/**
	 * Set results.
	 *
	 * @param results the results
	 */
	public void setResults(Results results){
		this.results = results;
	}

	/**
	 * Get results results.
	 *
	 * @return the results
	 */
	public Results getResults(){
		return results;
	}

	/**
	 * Set response time.
	 *
	 * @param responseTime the response time
	 */
	public void setResponseTime(int responseTime){
		this.responseTime = responseTime;
	}

	/**
	 * Get response time int.
	 *
	 * @return the int
	 */
	public int getResponseTime(){
		return responseTime;
	}

	/**
	 * Set message.
	 *
	 * @param message the message
	 */
	public void setMessage(List<String> message){
		this.message = message;
	}

	/**
	 * Get message list.
	 *
	 * @return the list
	 */
	public List<String> getMessage(){
		return message;
	}

	/**
	 * Set status.
	 *
	 * @param status the status
	 */
	public void setStatus(String status){
		this.status = status;
	}

	/**
	 * Get status string.
	 *
	 * @return the string
	 */
	public String getStatus(){
		return status;
	}

	@Override
 	public String toString(){
		return 
			"Response{" + 
			"results = '" + results + '\'' + 
			",responseTime = '" + responseTime + '\'' + 
			",message = '" + message + '\'' + 
			",status = '" + status + '\'' + 
			"}";
		}
}