package com.heidiaandahl.service;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.Generated;

/**
 * SeriesItem is a class generated by robopojogenerator to handle information from BLS api calls.
 */
@Generated("com.robohorse.robopojogenerator")
public class SeriesItem{

	@JsonProperty("data")
	private List<DataItem> data;

	@JsonProperty("seriesID")
	private String seriesID;

	/**
	 * Set data.
	 *
	 * @param data the data
	 */
	public void setData(List<DataItem> data){
		this.data = data;
	}

	/**
	 * Get data list.
	 *
	 * @return the list
	 */
	public List<DataItem> getData(){
		return data;
	}

	/**
	 * Set series id.
	 *
	 * @param seriesID the series id
	 */
	public void setSeriesID(String seriesID){
		this.seriesID = seriesID;
	}

	/**
	 * Get series id string.
	 *
	 * @return the string
	 */
	public String getSeriesID(){
		return seriesID;
	}

	@Override
 	public String toString(){
		return 
			"SeriesItem{" + 
			"data = '" + data + '\'' + 
			",seriesID = '" + seriesID + '\'' + 
			"}";
		}
}